steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - "${_IMAGE}"
      - --build-arg
      - "NEXT_PUBLIC_APP_ENV=${_NEXT_PUBLIC_APP_ENV}"
      - --build-arg
      - "NEXT_PUBLIC_EXPECTED_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_EXPECTED_FIREBASE_PROJECT_ID}"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}"
      - --build-arg
      - "NEXT_PUBLIC_RECAPTCHA_ENTERPRISE_SITE_KEY=${_NEXT_PUBLIC_RECAPTCHA_ENTERPRISE_SITE_KEY}"
      - .
images:
  - "${_IMAGE}"
options:
  logging: CLOUD_LOGGING_ONLY
